### ISSUE TITLE
Unable to compile test_opencl on aws image.

### ISSUE THREAD

**Issue by DhruvArora96** [HPCE/hpce-2017-cw3#58] opened 2017-10-30 17:45 UTC
I have ssh'd into a aws instance, i used the HPCE GPU image, and attempted to compile the test_opencl file and it resulted in the errors below. I do not understand what this error means and how to fix it.  Please advise.
![screenshot from 2017-10-30 17-41-17](https://user-images.githubusercontent.com/25771571/32186398-e2033068-bd99-11e7-8cda-7d7379b26328.png)
![screenshot from 2017-10-30 17-41-22](https://user-images.githubusercontent.com/25771571/32186399-e41f4bde-bd99-11e7-8ddf-3e36397ca7cb.png)

**Comment by m8pple** [comment] 2017-10-30 20:13
Possible duplicate of  #21 

An "undefined reference" means that it has found the function prototype in a header,
but cannot find the definition of the function (either in a source file or a library), e.g.:

https://stackoverflow.com/questions/22426574/gcc-undefined-reference-to

So you need to specify the library to link in for OpenCL, in the same way that we had
to specify it for TBB. But instead of `-ltbb`, we need `-lOpenCL`. So try:
```
g++ src/test_opencl  -std=c++11 -lOpenCL
```

You could also use the makefile, if you uncomment the line `# LDLIBS += -lOpenCL`, then do:
```
make bin/test_opencl
```

**Closed as completed** 2019-01-11 19:37 UTC
